### ISSUE TITLE
Is this shared on Bitrise StepLib?

### ISSUE THREAD

**Issue by provTheodoreNewell** [FutureWorkshops/bitrise-step-install-bundler#1]
I'd love to use this on Bitrise - have you shared it to the Bitrise StepLib ([described here](url
https://devcenter.bitrise.io/bitrise-cli/create-your-own-step/#sharing-a-new-step))?

**Comment by igorcferreira** [comment]
Thanks for the link @provTheodoreNewell! I'll check it, and try to push it to their system. I let you know if I succeed on doing so 😄

Thanks for the interest on using the step.

**Comment by igorcferreira** [comment]
@provTheodoreNewell I created a [PR to Bitrise](https://github.com/bitrise-io/bitrise-steplib/pull/1899) publishing the step. As soon as they approve it, it should be available for use.

**Comment by provTheodoreNewell** [comment]
Thanks @igorcferreira! Hopefully someone from Bitrise will help debug the failing status check...

**Comment by igorcferreira** [comment]
There was some mistakes on the `step.yml` file that was already fixed. And I re-shared it under a [new PR](https://github.com/bitrise-io/bitrise-steplib/pull/1900). It should be all fine now 😄

**Comment by trapacska** [comment]
It is shared now, thanks for the step! 🚀👑

**Comment by igorcferreira** [comment]
Thanks @trapacska for the status update 😄
