### ISSUE TITLE
Step invokes `bundle install` from the PWD

### ISSUE THREAD

**Issue by willmanio** [FutureWorkshops/bitrise-step-install-bundler#2]
Thanks for the great work.

This build step invokes `bundle install` from the parent process' PWD. Unless otherwise modified by a workflow step, this will be the `$BITRISE_SOURCE_DIR`.

This doesn't work so well for React Native projects, where the iOS code is located in an `ios` subdirectory.

As a result, the step publishes the message `Could not locate Gemfile` to the build log, which could be a red herring when debugging other issues.

Additionally, this introduces the possibility of a false positive condition. If `bundle install` is invoked in the wrong directory _and_ the installed Bundler version is sufficient, the step will go through the trouble of uninstalling and re-installing Bundler for no reason.

As a fix, I would suggest replacing the `Path to the Gemfile lock` input variable with a `Working directory` input variable. It should be assumed that `Gemfile.lock` lives within this directory. The [Yarn step](https://github.com/bitrise-community/steps-yarn) follows this pattern.

I'm happy to provide additional details or submit a PR.

**Comment by willmanio** [comment]
After some additional thought, I really question if this step should invoke `bundle install` at all. By invoking `bundle install`, the step is causing an undocumented and perhaps unwanted side effect (installing gems). That could be especially annoying if, like me, you want your gems installed to a specific path (`bundle install --path vendor/bundle`).

I think it's sufficient to query the system for the installed Bundler version, query `Gemfile.lock` for the necessary Bundler version, and take action if they differ. Attempting to short circuit this check via `bundle install` may be more headache than it's worth.

**Comment by zvs001** [comment]
I also have this issue. 
Example:
![bitrise](https://user-images.githubusercontent.com/25595191/58493258-31ebac80-817b-11e9-8e4a-4bd0f0562d81.jpg)

**Comment by chedabob** [comment]
@zvs001 @willmanio i've fixed these issues in a PR: https://github.com/FutureWorkshops/bitrise-step-install-bundler/pull/4

If you'd like to test, put theses lines in your bitrise.yml

```
- git::https://github.com/chedabob/bitrise-step-install-bundler:
        inputs:
        - gemfilelock_dir: "$FASTLANE_WORK_DIR"
```

**Comment by igorcferreira** [comment]
@willmanio The PR from @chedabob that handles this behaviour was just merged. Thanks for the report, and sorry that took so long to reply to it.

**Comment by willmanio** [comment]
@igorcferreira cheers, no worries! I'm looking forward to enabling this in our CI system today.

**Comment by igorcferreira** [comment]
@willmanio I just created the PR to Bitrise step repo. Hopefully this will be available soon
